# [START runtime]
runtime: nodejs
env: flex
# [END runtime]

# [START handlers]
handlers:
 - url: /
   secure: always
   redirect_http_response_code: 301
   static_files: build/index.html
   upload: build/index.html

 - url: /(.*)
   secure: always
   redirect_http_response_code: 301
   static_files: build/\1
   upload: build/(.*)
# [END handlers]
